# Cloud Build configuration for People Counting Frontend
# Builds and deploys Next.js app to Cloud Run
#
# Run from repo root: gcloud builds submit --config server_side/frontend/cloudbuild.yaml

steps:
  # Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/people-counting-frontend:$COMMIT_SHA"
      - "-t"
      - "gcr.io/$PROJECT_ID/people-counting-frontend:latest"
      - "--build-arg"
      - "NEXT_PUBLIC_API_URL=${_API_URL}"
      - "-f"
      - "server_side/frontend/Dockerfile"
      - "server_side/frontend"
    timeout: "600s"

  # Push the Docker image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/people-counting-frontend:$COMMIT_SHA"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/people-counting-frontend:latest"

  # Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "people-counting-frontend"
      - "--image"
      - "gcr.io/$PROJECT_ID/people-counting-frontend:$COMMIT_SHA"
      - "--region"
      - "${_REGION}"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--memory"
      - "512Mi"
      - "--cpu"
      - "1"
      - "--port"
      - "3000"
      - "--set-env-vars"
      - "NEXT_PUBLIC_API_URL=${_API_URL}"
      - "--min-instances"
      - "0"
      - "--max-instances"
      - "10"

# Substitution variables (override _API_URL with your backend URL)
substitutions:
  _REGION: "us-central1"
  _API_URL: "https://people-counting-api-zk43zjlhoq-uc.a.run.app"

# Build options
options:
  logging: CLOUD_LOGGING_ONLY

# Store images
images:
  - "gcr.io/$PROJECT_ID/people-counting-frontend:$COMMIT_SHA"
  - "gcr.io/$PROJECT_ID/people-counting-frontend:latest"

timeout: "600s"
